application: pointy-pointy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: static/images

- url: /styles
  static_dir: static/css

- url: /scripts
  static_dir: static/scripts

- url: /(.*\.ico)
  static_files: static/\1
  upload: static/(.*\.ico)
  mime_type: image/x-icon

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"